// <auto-generated />
using System;
using EntertainmentCatalog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntertainmentCatalog.Migrations
{
    [DbContext(typeof(EntertainmentCatalogContext))]
    partial class EntertainmentCatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EntertainmentCatalog.Models.Cataloge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("System");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Cataloge");
                });
#pragma warning restore 612, 618
        }
    }
}
